"""Generate dependency-free TypeScript declarations from the app's OpenAPI schema."""
import argparse
import json
import tempfile
from pathlib import Path


def ts_type(schema):
    if '$ref' in schema:
        return schema['$ref'].split('/')[-1]
    if 'const' in schema:
        return json.dumps(schema['const'], ensure_ascii=False)
    if 'enum' in schema:
        return ' | '.join(json.dumps(value, ensure_ascii=False) for value in schema['enum'])
    for union in ('anyOf', 'oneOf'):
        if union in schema:
            return ' | '.join(ts_type(part) for part in schema[union])
    if 'allOf' in schema:
        return ' & '.join('(' + ts_type(part) + ')' if 'anyOf' in part or 'oneOf' in part else ts_type(part) for part in schema['allOf'])
    kind = schema.get('type')
    if kind == 'array':
        return '(' + ts_type(schema['items']) + ')[]'
    if kind == 'object' or 'properties' in schema:
        required = schema.get('required', [])
        fields = [json.dumps(name) + ('' if name in required else '?') + ': ' + ts_type(value) for name, value in schema.get('properties', {}).items()]
        if fields:
            return '{ ' + '; '.join(fields) + ' }'
        additional = schema.get('additionalProperties', {})
        return 'Record<string, ' + (ts_type(additional) if isinstance(additional, dict) else 'unknown') + '>'
    return {'string': 'string', 'integer': 'number', 'number': 'number', 'boolean': 'boolean', 'null': 'null'}.get(kind, 'unknown')


def render_types(schema):
    return '// Generated by python -m muse.openapi_types; do not edit.\n' + ''.join(
        f'export type {name} = {ts_type(model)};\n' for name, model in sorted(schema['components']['schemas'].items()))


def main():
    from pydantic import SecretStr

    from muse.config import Settings
    from muse.main import create_app
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(dir='work', prefix='openapi-') as directory:
        app = create_app(Settings(data_dir=Path(directory) / 'state', access_token=SecretStr('schema-generation-only')))
        content = render_types(app.openapi())
        app.state.repository.db.engine.dispose()
    target = Path('frontend/src/api.generated.ts')
    if args.check:
        if not target.exists() or target.read_text(encoding='utf-8') != content:
            raise SystemExit('Generated API declarations are stale; run python -m muse.openapi_types')
    else:
        target.write_text(content, encoding='utf-8')

if __name__ == '__main__':
    main()
