import {useEffect,useRef,useState} from 'react';
import {ui,uiFeedback} from '../i18n';
import type {Api} from './api';
import type {StoreProject,StoreReadinessReport} from '../api.generated';
const labels:Record<string,string>={policy:'店铺政策',shipping:'配送设置',payment:'支付设置',domain:'店铺域名',design:'网站设计',products:'商品资料',verification:'独立购买验证',tax:'税务设置'};
export function StoreReadiness({api,project,onAction}:{api:Api;project:StoreProject;onAction:(value:string)=>void}){
 const [refresh,setRefresh]=useState(0),[report,setReport]=useState<StoreReadinessReport|null>(null),[error,setError]=useState(''),[rate,setRate]=useState('6.00'),[threshold,setThreshold]=useState('50.00'),[subtotal,setSubtotal]=useState('49.99'),[quote,setQuote]=useState('');
 const scope=project.id+':'+project.revision,active=useRef(scope),generation=useRef(0),quoteRequest=useRef(0);
 if(active.current!==scope){active.current=scope;generation.current++;quoteRequest.current++;}
 useEffect(()=>{setQuote('');setRate('6.00');setThreshold('50.00');setSubtotal('49.99');return()=>{generation.current++;quoteRequest.current++;};},[scope]);
 useEffect(()=>{let live=true;setReport(null);setError('');api<StoreReadinessReport>(`/commerce/projects/${project.id}/readiness`).then(value=>{if(live)setReport(value);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[api,project.id,project.revision,refresh]);
 async function calculate(){const start=generation.current,request=++quoteRequest.current;setError('');setQuote('');try{const value=await api<{amount:string;currency:string}>(`/commerce/projects/${project.id}/shipping-quote`,{method:'POST',body:JSON.stringify({country:'AU',rate,free_from:threshold||null,subtotal})});if(start===generation.current&&request===quoteRequest.current)setQuote(value.amount+' '+value.currency);}catch(e){if(start===generation.current&&request===quoteRequest.current)setError(e instanceof Error?e.message:'Error');}}
 return <section className="commerce-card" data-testid="store-readiness"><h2>{ui('开店检查')}</h2><button onClick={()=>setRefresh(value=>value+1)}>{ui('刷新检查')}</button><p>{ui('已配置和已验证分别显示；正式发布以对应版本的发布审查为准。')}</p>
 {report?.items.map(item=><div className="crew-readiness-row" key={item.key} data-testid={`readiness-${item.key}`}><b>{ui(labels[item.key])}</b><span>{ui(item.configuration_status==='CONFIGURED'?'已配置':'待配置')}</span><span>{ui(item.verification_status==='VERIFIED_STAGING'?'测试站已验证':'需独立验证')}</span><div className="commerce-actions">{item.configuration_url?<a className="crew-platform-settings" href={item.configuration_url} target="_blank" rel="noreferrer">{ui('打开店铺配置')}</a>:<button onClick={()=>onAction(item.action)}>{ui('前往处理')}</button>}{item.confirmation_url&&<a className="crew-platform-settings" href={item.confirmation_url} target="_blank" rel="noreferrer">{ui('确认店铺配置')}</a>}</div>{item.confirmation_url&&<small className="crew-readiness-hint">{ui('先在 WooCommerce 配置，再由商家确认。完成后重新连接并刷新店铺上下文；购买验证仍需独立运行。')}</small>}</div>)}
 <details><summary>{ui('运费预估工具')}</summary><p>{ui('仅计算示例运费，不会修改店铺配送规则。')}</p><label>{ui('固定运费')}<input type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(e.target.value)}/></label><label>{ui('免运门槛')}<input type="number" min="0" step="0.01" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label><label>{ui('购物车小计')}<input type="number" min="0" step="0.01" value={subtotal} onChange={e=>setSubtotal(e.target.value)}/></label><button onClick={()=>void calculate()}>{ui('计算预估')}</button>{quote&&<p role="status">{quote}</p>}</details>
 {error&&<p role="alert" className="error">{uiFeedback(error)}</p>}</section>;
}
