<?php
/** Product-maintained theme bootstrap. Never generated by an Agent. */
if (!defined('ABSPATH')) { exit; }
add_action('after_setup_theme', static function () {
    add_theme_support('woocommerce');
});
add_action('wp_enqueue_scripts', static function () {
    wp_enqueue_style('muse-storefront', get_theme_file_uri('assets/storefront.css'), array(), wp_get_theme()->get('Version'));
});
