"""Offline native-theme renderer and deterministic package integrity checks.

These checks do not prove WordPress rendering, purchase flow or execution isolation.
There is deliberately no deployment or arbitrary filesystem extraction here.
"""
import hashlib
import io
import json
import re
import stat
import zipfile
from html import escape
from html.parser import HTMLParser
from pathlib import Path

from muse.commerce.models import ProductDraft, SiteBlueprint, SitePackage
from muse.commerce.repository import digest, encode

MAX_FILE = 512 * 1024
MAX_PACKAGE = 5 * 1024 * 1024
TEMPLATES = {'index', 'page', 'front-page', 'archive-product', 'single-product',
             'page-cart', 'page-checkout', 'page-about', 'page-contact'}
ALLOWED_FILES = {'style.css', 'theme.json', 'functions.php', 'assets/storefront.css',
                 'parts/header.html', 'parts/footer.html'} | {f'templates/{name}.html' for name in TEMPLATES}
FIXED_FUNCTIONS = b'''<?php
/** Product-maintained theme bootstrap. Never generated by an Agent. */
if (!defined('ABSPATH')) { exit; }
add_action('after_setup_theme', static function () {
    add_theme_support('woocommerce');
});
add_action('wp_enqueue_scripts', static function () {
    wp_enqueue_style('muse-storefront', get_theme_file_uri('assets/storefront.css'), array(), wp_get_theme()->get('Version'));
});
'''
BLOCKS = {'image', 'group', 'heading', 'paragraph', 'post-title', 'post-content', 'site-title',
          'template-part', 'navigation', 'navigation-link', 'query-pagination',
          'query-pagination-previous', 'query-pagination-next', 'query-pagination-numbers',
          'woocommerce/product-collection', 'woocommerce/product-template',
          'woocommerce/product-image', 'woocommerce/product-title', 'woocommerce/product-price',
          'woocommerce/product-button', 'woocommerce/product-summary', 'woocommerce/add-to-cart-form',
          'woocommerce/product-details', 'woocommerce/cart', 'woocommerce/checkout'}
TRANSACTION_BLOCKS = {
    'filled-cart-block', 'empty-cart-block', 'cart-items-block', 'cart-line-items-block', 'cart-totals-block',
    'cart-order-summary-block', 'cart-order-summary-heading-block', 'cart-order-summary-coupon-form-block',
    'cart-order-summary-subtotal-block', 'cart-order-summary-fee-block', 'cart-order-summary-discount-block',
    'cart-order-summary-shipping-block', 'cart-order-summary-taxes-block', 'cart-express-payment-block',
    'proceed-to-checkout-block', 'cart-accepted-payment-methods-block', 'checkout-fields-block',
    'checkout-express-payment-block', 'checkout-contact-information-block', 'checkout-shipping-method-block',
    'checkout-pickup-options-block', 'checkout-shipping-address-block', 'checkout-billing-address-block',
    'checkout-shipping-methods-block', 'checkout-payment-block', 'checkout-additional-information-block',
    'checkout-order-note-block', 'checkout-terms-block', 'checkout-actions-block', 'checkout-totals-block',
    'checkout-order-summary-block', 'checkout-order-summary-cart-items-block', 'checkout-order-summary-subtotal-block',
    'checkout-order-summary-fee-block', 'checkout-order-summary-discount-block', 'checkout-order-summary-coupon-form-block',
    'checkout-order-summary-shipping-block', 'checkout-order-summary-taxes-block',
}
BLOCKS |= {'woocommerce/' + name for name in TRANSACTION_BLOCKS}


def transaction_container(name: str, children: str = '') -> str:
    """Native Woo components require saved wrappers and their nested block layout."""
    return block('woocommerce/' + name, inner='<div data-block-name="woocommerce/' + name +
                 '" class="wp-block-woocommerce-' + name + '">\n' + children + '</div>')


def transaction_block(kind: str) -> str:
    if kind == 'cart':
        summary = transaction_container('cart-order-summary-block', ''.join(transaction_container('cart-order-summary-' + item + '-block')
            for item in ('heading', 'coupon-form', 'subtotal', 'fee', 'discount', 'shipping', 'taxes')))
        totals = transaction_container('cart-totals-block', summary + ''.join(transaction_container(name) for name in (
            'cart-express-payment-block', 'proceed-to-checkout-block', 'cart-accepted-payment-methods-block')))
        filled = transaction_container('filled-cart-block', transaction_container('cart-items-block',
            transaction_container('cart-line-items-block')) + totals)
        empty = transaction_container('empty-cart-block', block('heading', {'level': 2},
            '<h2 class="wp-block-heading">Your cart is currently empty!</h2>'))
        return transaction_container('cart', filled + empty)
    fields = transaction_container('checkout-fields-block', ''.join(transaction_container('checkout-' + item + '-block')
        for item in ('express-payment', 'contact-information', 'shipping-method', 'pickup-options', 'shipping-address',
                     'billing-address', 'shipping-methods', 'payment', 'additional-information', 'order-note', 'terms', 'actions')))
    totals = transaction_container('checkout-totals-block', transaction_container('checkout-order-summary-block',
        ''.join(transaction_container('checkout-order-summary-' + item + '-block')
                for item in ('cart-items', 'subtotal', 'fee', 'discount', 'coupon-form', 'shipping', 'taxes'))))
    return transaction_container('checkout', fields + totals)


def block(name: str, attrs: dict | None = None, inner: str | None = None) -> str:
    # JSON in a comment must not contain comment terminators or HTML delimiters.
    attributes = '' if not attrs else ' ' + encode(attrs).replace('&', '\\u0026').replace('<', '\\u003c').replace('>', '\\u003e')
    if inner is None:
        return f'<!-- wp:{name}{attributes} /-->\n'
    return f'<!-- wp:{name}{attributes} -->\n{inner}\n<!-- /wp:{name} -->\n'


def frame(inner: str) -> str:
    return (block('template-part', {'slug': 'header', 'tagName': 'header'}) +
            block('group', {'tagName': 'main', 'layout': {'type': 'constrained'}},
                  '<main class="wp-block-group">\n' + inner + '</main>') +
            block('template-part', {'slug': 'footer', 'tagName': 'footer'}))


def seed_files() -> dict[str, bytes]:
    installed = Path(__file__).parent / 'assets' / 'storefront'
    root = installed if installed.is_dir() else Path(__file__).resolve().parents[3] / 'wordpress' / 'muse-storefront'
    # Read only the fixed manifest; never walk an Agent-controlled directory.
    files = {name: (root / name).read_bytes() for name in ALLOWED_FILES}
    if files['functions.php'] != FIXED_FUNCTIONS:
        raise ValueError('Immutable theme code differs from the product baseline')
    return files


def render_site_files(blueprint: SiteBlueprint, drafts: list[ProductDraft]) -> dict[str, bytes]:
    blueprint = SiteBlueprint.model_validate(blueprint.model_dump())
    if len(drafts) > 20:
        raise ValueError('At most twenty product drafts are supported')
    checked = [ProductDraft.model_validate(item.model_dump()) for item in drafts]
    if len({item.sku.casefold() for item in checked}) != len(checked):
        raise ValueError('Duplicate product SKU')
    slugs = {page.slug for page in blueprint.pages}
    if any(item.slug not in slugs for item in blueprint.navigation):
        raise ValueError('Navigation must reference a blueprint page')
    colors = {key: blueprint.design_tokens.get(key) for key in ('background', 'text', 'accent')}
    if any(not isinstance(value, str) or not re.fullmatch(r'#[0-9a-fA-F]{6}', value) for value in colors.values()):
        raise ValueError('Theme colors must be six-digit hex values')
    files = seed_files()
    theme = json.loads(files['theme.json'])
    theme['settings']['color']['palette'] = [{'slug': key, 'name': key.title(), 'color': value} for key, value in colors.items()]
    theme['styles']['color'] = {'background': colors['background'], 'text': colors['text']}
    font = blueprint.design_tokens.get('font', 'sans')
    if font not in {'sans', 'serif'}: raise ValueError('Unsupported theme font')
    if 'font' in blueprint.design_tokens:
        theme['styles'].setdefault('typography', {})['fontFamily'] = 'Georgia, serif' if font == 'serif' else 'Arial, sans-serif'
    files['theme.json'] = (encode(theme) + '\n').encode('utf-8')
    navigation = ''.join(block('navigation-link', {'label': escape(item.label), 'url': '/' + item.slug + '/'}) for item in blueprint.navigation)
    files['parts/header.html'] = block('group', {'layout': {'type': 'flex', 'justifyContent': 'space-between'}},
        '<div class="wp-block-group">\n' + block('site-title') + block('navigation', {'overlayMenu': 'mobile'}, navigation) + '</div>').encode()
    titles = {page.kind: page.title for page in blueprint.pages}
    for kind, template in {'home': 'front-page', 'cart': 'page-cart', 'checkout': 'page-checkout',
                           'about': 'page-about', 'contact': 'page-contact'}.items():
        heading = block('heading', {'level': 1}, '<h1 class="wp-block-heading">' + escape(titles[kind]) + '</h1>')
        body = transaction_block(kind) if kind in {'cart', 'checkout'} else block('post-content')
        if kind == 'home':
            design = blueprint.required_settings.get('store_design')
            if design:
                from muse.commerce.design_models import StoreDesignDocument
                from muse.commerce.design_render import render_design
                body = render_design(StoreDesignDocument.model_validate(design), blueprint.required_settings.get('design_media_urls'))
                heading = ''
            else:
                body += product_collection(inherit=False)
        files[f'templates/{template}.html'] = frame(heading + body).encode('utf-8')
    files['templates/archive-product.html'] = frame(block('heading', {'level': 1},
        '<h1 class="wp-block-heading">' + escape(titles['shop']) + '</h1>') + product_collection()).encode('utf-8')
    files['templates/single-product.html'] = frame(block('post-title', {'level': 1, 'isLink': False}) +
        ''.join(block(name) for name in ('woocommerce/product-image', 'woocommerce/product-price',
                                       'woocommerce/add-to-cart-form', 'woocommerce/product-details'))).encode('utf-8')
    if blueprint.required_settings.get('store_design'):
        files['assets/storefront.css'] += b'\n.crew-design-section{padding:48px 24px}.crew-design-hero{padding:80px 24px}.crew-design-button{display:inline-block;padding:12px 20px;border:1px solid currentColor;border-radius:6px}\n'
    validate_theme_files(files)
    return files


def product_collection(*, inherit: bool = True) -> str:
    return block('woocommerce/product-collection', {'query': {'perPage': 12, 'postType': 'product', 'inherit': inherit},
        'displayLayout': {'type': 'flex', 'columns': 3}}, block('woocommerce/product-template', inner=
            block('woocommerce/product-image') + block('post-title', {'level': 2, 'isLink': True}) +
            block('woocommerce/product-price') + block('woocommerce/product-button')))


class StaticHTML(HTMLParser):
    """Conservative content check; WordPress block-schema validation remains pending."""
    def handle_starttag(self, tag, attrs):
        if tag not in {'figure', 'img', 'main', 'div', 'header', 'footer', 'section', 'p', 'span', 'a', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'br'}:
            raise ValueError('Unsupported HTML element')
        for name, value in attrs:
            if name.startswith('on') or name not in {'class', 'id', 'role', 'href', 'src', 'alt', 'aria-label', 'data-block-name'}:
                raise ValueError('Unsupported HTML attribute')
            if name in {'src','alt'} and tag != 'img':
                raise ValueError('Image attribute outside image')
            if name == 'src' and (not re.fullmatch(r'/wp-content/uploads/[a-zA-Z0-9_./-]+', value or '') or '..' in value):
                raise ValueError('Unsupported media source')
            if name == 'href' and not re.fullmatch(r'/([a-z0-9-][a-z0-9/-]*)?|#[a-z0-9-]+', value or ''):
                raise ValueError('Unsupported link target')
            if name == 'data-block-name' and value not in BLOCKS:
                raise ValueError('Unsupported component name')

    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)

    def handle_decl(self, decl):
        raise ValueError('HTML declarations are not supported')


def _validate_block_paths(value) -> None:
    if isinstance(value, dict):
        for key, item in value.items():
            if key.lower() in {'url', 'href', 'src'} and (
                not isinstance(item, str) or '..' in item or
                not re.fullmatch(r'/([a-zA-Z0-9_-][a-zA-Z0-9_./-]*)?|#[a-zA-Z0-9_-]+', item)
            ):
                raise ValueError('Unsupported block attribute path')
            _validate_block_paths(item)
    elif isinstance(value, list):
        for item in value:
            _validate_block_paths(item)


def validate_theme_files(files: dict[str, bytes]) -> None:
    if set(files) != ALLOWED_FILES:
        raise ValueError('Theme file manifest differs from the product allowlist')
    if files['functions.php'] != FIXED_FUNCTIONS:
        raise ValueError('Immutable theme code changed')
    if any(len(content) > MAX_FILE for content in files.values()) or sum(map(len, files.values())) > MAX_PACKAGE:
        raise ValueError('Theme exceeds the package size limit')
    for name, content in files.items():
        if name == 'functions.php':
            continue
        value = content.decode('utf-8')
        if '<?' in value or '\x00' in value:
            raise ValueError('Executable content is not allowed')
        if name.endswith('.css') and re.search(r'\\|@import|url\s*\(|expression\s*\(|behavior\s*:', value, re.IGNORECASE):
            raise ValueError('External or executable CSS is not supported')
        if name == 'theme.json':
            settings = json.loads(value)
            _validate_block_paths(settings)
            if settings.get('version') != 3 or re.search(r'https?:|javascript:|data:|url\s*\(|@import|\\', value, re.IGNORECASE):
                raise ValueError('Unsupported theme settings')
        if name.endswith('.html'):
            parser = StaticHTML(convert_charrefs=True)
            parser.feed(value)
            parser.close()
            for match in re.finditer(r'<!--\s*/?wp:([^\s>]+)(.*?)-->', value, re.DOTALL):
                if match[1] not in BLOCKS:
                    raise ValueError('Unsupported WordPress block')
                attrs = match[2].strip().removesuffix('/').strip()
                if attrs:
                    # Block attributes may be JSON, never arbitrary HTML or a remote URL.
                    decoded = json.loads(attrs)
                    if not isinstance(decoded, dict):
                        raise ValueError('Unsupported block attribute object')
                    _validate_block_paths(decoded)
                    if re.search(r'https?:|javascript:|data:|<|>', encode(decoded), re.IGNORECASE):
                        raise ValueError('Unsupported block attribute')


def build_site_archive(blueprint: SiteBlueprint, drafts: list[ProductDraft], *, code_revision: str) -> tuple[SitePackage, bytes]:
    return build_file_archive(render_site_files(blueprint, drafts), code_revision=code_revision,
        content_hash=digest({'blueprint': blueprint.model_dump(mode='json'), 'products': [p.model_dump(mode='json') for p in drafts]}))


def build_file_archive(files: dict[str, bytes], *, code_revision: str, content_hash: str) -> tuple[SitePackage, bytes]:
    """Package a captured, validated static code result; never accept executable additions."""
    if not re.fullmatch(r'[0-9a-f]{40}', code_revision):
        raise ValueError('A full source commit revision is required')
    if not re.fullmatch(r'[0-9a-f]{64}', content_hash):
        raise ValueError('A frozen business content hash is required')
    files = dict(files)
    validate_theme_files(files)
    output = io.BytesIO()
    with zipfile.ZipFile(output, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for name, content in sorted(files.items()):
            info = zipfile.ZipInfo('muse-storefront/' + name, date_time=(1980, 1, 1, 0, 0, 0))
            info.create_system = 3
            info.external_attr = (stat.S_IFREG | 0o644) << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(info, content)
    data = output.getvalue()
    manifest = [{'path': name, 'sha256': hashlib.sha256(content).hexdigest(), 'bytes': len(content)} for name, content in sorted(files.items())]
    metadata = SitePackage(code_revision=code_revision, files_manifest=manifest,
        package_sha256=hashlib.sha256(data).hexdigest(), immutable_code_sha256=hashlib.sha256(FIXED_FUNCTIONS).hexdigest(),
        content_sha256=content_hash)
    validate_site_archive(data, metadata)
    return metadata, data


def validate_site_archive(data: bytes, metadata: SitePackage) -> SitePackage:
    if len(data) > MAX_PACKAGE or hashlib.sha256(data).hexdigest() != metadata.package_sha256:
        raise ValueError('Package digest or size differs')
    if metadata.immutable_code_sha256 != hashlib.sha256(FIXED_FUNCTIONS).hexdigest():
        raise ValueError('Immutable code digest differs')
    files: dict[str, bytes] = {}
    try:
        with zipfile.ZipFile(io.BytesIO(data)) as archive:
            entries = archive.infolist()
            if len(entries) != len(ALLOWED_FILES) or sum(info.file_size for info in entries) > MAX_PACKAGE:
                raise ValueError('Archive manifest or size differs')
            for info in entries:
                name = info.filename.removeprefix('muse-storefront/')
                mode = info.external_attr >> 16
                if (info.filename != 'muse-storefront/' + name or name not in ALLOWED_FILES or name in files
                        or info.file_size > MAX_FILE or stat.S_ISLNK(mode)
                        or info.compress_type not in {zipfile.ZIP_STORED, zipfile.ZIP_DEFLATED} or info.flag_bits & 1):
                    raise ValueError('Unsupported archive entry')
                files[name] = archive.read(info)
    except (zipfile.BadZipFile, RuntimeError, OSError) as exc:
        raise ValueError('Invalid theme archive') from exc
    validate_theme_files(files)
    manifest = [{'path': name, 'sha256': hashlib.sha256(content).hexdigest(), 'bytes': len(content)} for name, content in sorted(files.items())]
    if manifest != metadata.files_manifest:
        raise ValueError('File manifest differs')
    return metadata


def render_owned_site(blueprint: SiteBlueprint, drafts: list[ProductDraft], *, code_revision: str) -> SitePackage:
    return build_site_archive(blueprint, drafts, code_revision=code_revision)[0]
