import React, { useCallback, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { ArrowUp, ArrowUpRight, BookOpen, Check, ChevronRight, CircleHelp, Code2, Download, FileText, FolderOpen, Globe2, History, Layers3, LoaderCircle, LockKeyhole, Pause, Play, Plus, Search, Settings2, ShieldCheck, Sparkles, Square, Trash2, X } from 'lucide-react';
import './style.css';

import type {TaskView as Task, WorkspaceView as Workspace, EventView as Event, ArtifactView as Artifact, SourceView as Source, ApprovalView as Approval, MemoryView as Memory, FileChangeView as FileChange, UncertainActionView as UncertainAction} from './api.generated';
const statusNames:Record<string,string> = {QUEUED:'排队中',RUNNING:'进行中',WAITING_INPUT:'等待补充',WAITING_APPROVAL:'等待批准',PAUSED:'已暂停',INTERRUPTED:'需要核对',SUCCEEDED:'已完成',FAILED:'未完成',CANCELLED:'已取消'};
const terminal = new Set(['SUCCEEDED','FAILED','CANCELLED']);
const modes = [{id:'general',name:'自由任务',icon:Sparkles,desc:'从一个想法开始'}, {id:'research',name:'网页研究',icon:Globe2,desc:'阅读来源，形成有据可查的报告'}, {id:'documents',name:'资料整理',icon:FileText,desc:'提取、分类，保留每份原件'}, {id:'coding',name:'编程助手',icon:Code2,desc:'理解代码、修改并运行验证'}];
const samples:Record<string,string> = {research:'阅读这些公开网页，比较关键差异并生成带来源引用的报告：\n',documents:'阅读工作区中的 TXT、Markdown 和文本 PDF，提取要点并生成摘要报告，保留原文件。',coding:'先阅读项目结构，说明入口、主要模块和测试命令，暂时不要修改代码。'};
function Markdown({text}:{text:string}) { return <div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{a:props=><a {...props} target="_blank" rel="noopener noreferrer"/>,img:props=><span>[图片：{props.alt}]</span>}}>{text}</ReactMarkdown></div>; }

function App() {
  const [token,setToken] = useState(()=>sessionStorage.getItem('muse-token')||'');
  const [entered,setEntered] = useState(false), [tokenInput,setTokenInput] = useState('');
  const [error,setError] = useState(''), [busy,setBusy] = useState(false);
  const [tasks,setTasks] = useState<Task[]>([]), [workspaces,setWorkspaces] = useState<Workspace[]>([]), [workspace,setWorkspace] = useState('');
  const [selected,setSelected] = useState<string|null>(null), [task,setTask] = useState<Task|null>(null);
  const [events,setEvents] = useState<Event[]>([]), [artifacts,setArtifacts] = useState<Artifact[]>([]), [sources,setSources] = useState<Source[]>([]), [approvals,setApprovals] = useState<Approval[]>([]);
  const [prompt,setPrompt] = useState(''), [scenario,setScenario] = useState('general'), [search,setSearch] = useState('');
  const [model,setModel] = useState('未配置'), [tab,setTab] = useState('成果');
  const [modal,setModal] = useState<'memory'|'workspace'|null>(null), [memories,setMemories] = useState<Memory[]>([]);
  const [memoryTitle,setMemoryTitle] = useState(''), [memoryContent,setMemoryContent] = useState(''), [memoryScope,setMemoryScope] = useState('project'), [memoryId,setMemoryId] = useState<string|null>(null);
  const [workspacePath,setWorkspacePath] = useState(''), [workspaceName,setWorkspaceName] = useState('');
  const [reply,setReply] = useState('');
  const [fileHistory,setFileHistory] = useState<FileChange[]>([]);
  const [children,setChildren] = useState<Task[]>([]);
  const [uncertainActions,setUncertainActions] = useState<UncertainAction[]>([]);
  const [reconciliationNotes,setReconciliationNotes] = useState<Record<string,string>>({});
  const cursor = useRef(0), active = useRef<string|null>(null);
  const submission = useRef<{payload:string;id:string}|null>(null);
  const api = useCallback(async <T,>(path:string, init:RequestInit={}):Promise<T> => {
    const response=await fetch('/api'+path,{...init,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...init.headers}});
    if(!response.ok) {if(response.status===401)setEntered(false); const body=await response.json().catch(()=>({})); throw new Error(typeof body.detail==='string'?body.detail:'请求未完成，请检查输入或稍后重试');}
    return response.status===204 ? undefined as T : response.json();
  },[token]);
  const act = async (operation:()=>Promise<void>)=>{setBusy(true);setError('');try{await operation();}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}};
  const refresh = useCallback(async()=>{
    const [list,spaces,settings]=await Promise.all([api<Task[]>('/tasks'),api<Workspace[]>('/workspaces'),api<{provider?:{model:string}}>('/settings')]);
    setTasks(list);setWorkspaces(spaces);setWorkspace(value=>value||spaces[0]?.id||'');setModel(settings.provider?.model||'未配置');setEntered(true);
  },[api]);
  useEffect(()=>{if(token){sessionStorage.setItem('muse-token',token);refresh().catch(e=>setError(e.message));}},[token,refresh]);
  useEffect(()=>{if(!entered)return;const timer=setInterval(()=>refresh().catch(e=>setError(e.message)),4000);return()=>clearInterval(timer);},[entered,refresh]);
  const refreshTask = useCallback(async(id:string)=>{
    const [detail,files,links,pending,changes,childTasks,uncertain]=await Promise.all([api<Task>('/tasks/'+id),api<Artifact[]>('/tasks/'+id+'/artifacts'),api<Source[]>('/tasks/'+id+'/sources'),api<Approval[]>('/approvals?task_id='+id),api<FileChange[]>('/tasks/'+id+'/file-history'),api<Task[]>('/tasks/'+id+'/children'),api<UncertainAction[]>('/tasks/'+id+'/uncertain-actions')]);
    if(active.current!==id)return;
    setTask(detail);setArtifacts(files);setSources(links);setApprovals(pending.filter(x=>x.status==='PENDING'));setTasks(list=>list.map(t=>t.id===id?detail:t));
    setFileHistory(changes);
    setChildren(childTasks);setUncertainActions(uncertain);
  },[api]);
  useEffect(()=>{
    active.current=selected;setTask(null);setEvents([]);setArtifacts([]);setSources([]);setApprovals([]);setChildren([]);setUncertainActions([]);setReconciliationNotes({});cursor.current=0;setReply('');
    if(!selected||!entered)return;
    const id=selected, controller=new AbortController();let stopped=false;
    const stream=async()=>{
      while(!stopped){
        try{
          await refreshTask(id);
          const response=await fetch(`/api/tasks/${id}/events?after=${cursor.current}`,{headers:{Authorization:'Bearer '+token},signal:controller.signal});
          if(!response.ok||!response.body)throw new Error('事件连接中断，正在重连');
          const reader=response.body.getReader(), decoder=new TextDecoder();let buffer='';
          while(!stopped){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let index:number;
            while((index=buffer.indexOf('\n\n'))>=0){const frame=buffer.slice(0,index);buffer=buffer.slice(index+2);const line=frame.split('\n').find(x=>x.startsWith('data: '));if(!line)continue;
              const event=JSON.parse(line.slice(6)) as Event;
              if(event.sequence>cursor.current&&active.current===id){cursor.current=event.sequence;setEvents(old=>[...old,event]);if(['status','artifact','approval_required','approval_renewed','assistant_message','input_required'].includes(event.type))await refreshTask(id);}
            }
          }
          await refreshTask(id);
        }catch(e){if(!stopped)setError(e instanceof Error?e.message:'连接中断');}
        if(!stopped)await new Promise(resolve=>setTimeout(resolve,1800));
      }
    };void stream();const timer=setInterval(()=>refreshTask(id).catch(()=>{}),2500);
    return()=>{stopped=true;controller.abort();clearInterval(timer);};
  },[selected,entered,token,refreshTask]);
  const createTask=async(parent?:Task)=>{if(!prompt.trim())return;await act(async()=>{
    const payload={prompt,scenario:parent?.scenario||scenario,workspace_id:parent?.workspace_id||workspace,parent_task_id:parent?.id||null};
    const key=JSON.stringify(payload);
    if(submission.current?.payload!==key)submission.current={payload:key,id:crypto.randomUUID()};
    const created=await api<Task>('/tasks',{method:'POST',body:JSON.stringify({...payload,client_request_id:submission.current!.id})});
    submission.current=null;
    setSelected(created.id);setPrompt('');await refresh();
  });};
  const control=async(action:string,content='')=>{if(!task)return;const id=task.id;await act(async()=>{const changed=await api<Task>(`/tasks/${id}/${action}`,{method:'POST',body:JSON.stringify({expected_revision:task.revision,content})});if(active.current===id){setTask(changed);setReply('');}await refresh();});};
  const reconcileExternal=async(item:UncertainAction,successful:boolean)=>act(async()=>{if(!task)return;await api('/external-actions/'+task.id+'/reconcile',{method:'POST',body:JSON.stringify({call_id:item.id,action_digest:item.digest,expected_revision:task.revision,successful,explanation:reconciliationNotes[item.id]||''})});await refreshTask(task.id);});
  const renew=async(item:Approval)=>act(async()=>{await api('/approvals/'+item.id+'/renew',{method:'POST',body:JSON.stringify({action_digest:item.action_digest})});if(task)await refreshTask(task.id);});
  const decide=async(item:Approval,allow:boolean)=>act(async()=>{await api('/approvals/'+item.id+'/decision',{method:'POST',body:JSON.stringify({allow,action_digest:item.action_digest})});if(task)await refreshTask(task.id);});
  const download=async(file:Artifact)=>act(async()=>{const response=await fetch('/api/artifacts/'+file.id,{headers:{Authorization:'Bearer '+token}});if(!response.ok)throw new Error('下载失败');const url=URL.createObjectURL(await response.blob()),link=document.createElement('a');link.href=url;link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  const openMemory=()=>act(async()=>{setMemories(await api('/memories'));setModal('memory');});
  const saveMemory=()=>act(async()=>{await api('/memories'+(memoryId?'/'+memoryId:''),{method:memoryId?'PATCH':'POST',body:JSON.stringify({scope:memoryScope,title:memoryTitle,content:memoryContent,workspace_id:memoryScope==='project'?workspace:null})});setMemoryId(null);setMemoryTitle('');setMemoryContent('');setMemories(await api('/memories'));});
  const chosenSpace=workspaces.find(x=>x.id===(task?.workspace_id||workspace));
  const taskMessages=events.filter(e=>e.type==='assistant_message'&&String(e.payload.text||'').trim());
  const lastAssistant=events.reduce((last,e,index)=>e.type==='assistant_message'?index:last,-1);
  const streaming=events.slice(lastAssistant+1).filter(e=>e.type==='text_delta').map(e=>String(e.payload.text||'')).join('');
  const allDone=task&&terminal.has(task.status);

  if(!entered)return <main className="login"><div className="login-card"><div className="brand"><span className="brand-icon"><Layers3 size={25}/></span>MUSE</div><h1>你的想法，<br/>从这里开始。</h1><p>研究网页、整理资料、完成编程任务。<br/>连接这台电脑上的 MUSE 工作台。</p><label htmlFor="token">本地访问令牌</label><input id="token" type="password" autoComplete="off" value={tokenInput} onChange={e=>setTokenInput(e.target.value)} placeholder="从启动窗口复制访问令牌" onKeyDown={e=>{if(e.key==='Enter')setToken(tokenInput.trim());}}/><button className="primary" onClick={()=>{if(token===tokenInput.trim())void act(refresh);else setToken(tokenInput.trim());}} disabled={!tokenInput.trim()}>进入工作台 <ArrowUpRight size={17}/></button>{error&&<p role="alert" className="error">{error}</p>}<small><LockKeyhole size={14}/> 这是本机访问令牌，不是模型 API 密钥</small></div><div className="login-art"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><Layers3 size={115} strokeWidth={0.8}/><span>MAKE ROOM FOR WHAT MATTERS</span></div></main>;

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-icon"><Layers3 size={21}/></span>MUSE<span className="beta">LOCAL</span></div><button className="new-task" onClick={()=>{setSelected(null);setPrompt('');}}><Plus size={17}/>新建任务<span>＋</span></button><div className="nav-label">工作台</div><button className="nav-item selected" onClick={()=>setSelected(null)}><Layers3 size={17}/>全部任务<span>{tasks.length}</span></button><button className="nav-item" onClick={openMemory}><BookOpen size={17}/>记忆管理</button><div className="section-row"><span>最近任务</span><History size={14}/></div><div className="search"><Search size={14}/><input aria-label="搜索任务" placeholder="搜索任务" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="task-list">{tasks.filter(t=>t.prompt.toLowerCase().includes(search.toLowerCase())).map(t=><button key={t.id} className={'task-item '+(selected===t.id?'active':'')} onClick={()=>setSelected(t.id)}><span className={'dot '+t.status}/><span>{t.prompt}</span><small>{statusNames[t.status]}</small></button>)}{!tasks.length&&<p className="empty-small">任务会保存在这里，<br/>随时回来继续查看。</p>}</div><div className="sidebar-bottom"><button className="workspace-switch" onClick={()=>setModal('workspace')}><FolderOpen size={18}/><span>{chosenSpace?.name||'选择工作区'}<small>本地文件 · 明确授权</small></span><Settings2 size={15}/></button><div className="model-pill"><span className="dot SUCCEEDED"/><span>{model}</span><ShieldCheck size={14}/></div></div></aside>
    <main className="main"><header className="topbar"><span>个人工作台 <ChevronRight size={13}/><b>{task?'任务详情':'新的开始'}</b></span><div><span className="local-badge"><span/>本地运行</span><button className="icon-button" aria-label="工作区设置" onClick={()=>setModal('workspace')}><Settings2 size={18}/></button></div></header>
      {error&&<div className="banner error" role="alert">{error}<button aria-label="关闭错误" onClick={()=>setError('')}><X size={15}/></button></div>}
      {!selected?<div className="home"><div className="eyebrow"><span/>YOUR PERSONAL TASK ASSISTANT</div><h1>留出时间，<br/>做更重要的事<span>。</span></h1><p className="intro">把目标交给 MUSE。从查找资料到完成代码，<br/>让每一步都有进展，让每个结果有据可查。</p><section className="composer"><textarea placeholder="描述目标，让 MUSE 帮你完成…" value={prompt} onChange={e=>setPrompt(e.target.value)}/><div className="composer-footer"><select aria-label="选择工作区" value={workspace} onChange={e=>setWorkspace(e.target.value)}>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><button className="send" aria-label="开始任务" disabled={busy||!prompt.trim()||!workspace} onClick={()=>createTask()}><ArrowUp size={21}/></button></div></section><div className="mode-row">{modes.map(mode=><button key={mode.id} className={scenario===mode.id?'active':''} onClick={()=>setScenario(mode.id)}><mode.icon size={15}/>{mode.name}</button>)}</div><div className="section-row home-section"><span>从一个具体任务开始</span><small>想法 → 行动 → 成果</small></div><div className="starter-grid">{modes.slice(1).map(mode=><button key={mode.id} className="starter" onClick={()=>{setScenario(mode.id);setPrompt(samples[mode.id]);}}><div><mode.icon size={22} strokeWidth={1.5}/><ArrowUpRight size={16}/></div><h3>{mode.name}</h3><p>{mode.desc}</p></button>)}</div><div className="home-note"><ShieldCheck size={15}/><span>代码命令由你批准。关闭网页后，已启动的后台任务继续运行。</span></div></div>:
      <div className="task-layout"><section className="conversation">{task?<><div className="task-heading"><div className="eyebrow">{modes.find(m=>m.id===task.scenario)?.name} · {new Date(task.created_at*1000).toLocaleDateString('zh-CN')}</div><div className="heading-row"><h1 title={task.prompt}>{task.prompt.slice(0,75)}</h1><span className={'status '+task.status}>{statusNames[task.status]}</span></div><div className="task-actions">{['QUEUED','RUNNING'].includes(task.status)&&<button disabled={busy} onClick={()=>control('pause')}><Pause size={14}/>暂停</button>}{['PAUSED','INTERRUPTED'].includes(task.status)&&<button disabled={busy} onClick={()=>control('resume')}><Play size={14}/>继续执行</button>}{!terminal.has(task.status)&&<button disabled={busy} onClick={()=>control('cancel')}><Square size={13}/>取消任务</button>}</div></div><div className="user-message"><span>你的目标</span><p>{task.prompt}</p></div><div className="agent-label"><span className="mini-brand"><Layers3 size={15}/></span>MUSE<small>{model}</small></div>{taskMessages.map(event=><div className="message" key={event.sequence}><Markdown text={String(event.payload.text)}/></div>)}{streaming&&<div className="message"><Markdown text={streaming}/></div>}{!taskMessages.length&&!streaming&&<div className="waiting"><LoaderCircle size={17} className={task.status==='RUNNING'?'spin':''}/>{task.status==='QUEUED'?'任务已加入队列，等待 Worker 领取。':statusNames[task.status]}</div>}{task.error&&<div className="notice"><CircleHelp size={18}/><p>{task.error}</p></div>}{task.result&&!taskMessages.some(e=>e.payload.text===task.result)&&<Markdown text={task.result}/>}
      {uncertainActions.map(item=><div className="approval" key={item.id}><b>请核对中断前的操作结果</b><p>确认实际结果后记录结论，再继续任务。此操作不会重新执行命令，也不作为测试通过的凭证。</p><code>{item.name}: {JSON.stringify(item.arguments)}</code><textarea aria-label={'核对说明 '+item.id} value={reconciliationNotes[item.id]||''} onChange={e=>setReconciliationNotes(notes=>({...notes,[item.id]:e.target.value}))}/><div><button disabled={busy||!(reconciliationNotes[item.id]||'').trim()} onClick={()=>reconcileExternal(item,false)}>已确认失败</button><button disabled={busy||!(reconciliationNotes[item.id]||'').trim()} onClick={()=>reconcileExternal(item,true)}>已确认成功</button></div></div>)}
      {approvals.map(item=><div className="approval" key={item.id}><div className="approval-title"><ShieldCheck size={20}/><b>这一步需要你的批准</b></div><p>允许在当前工作区执行以下命令？命令拥有当前系统用户的权限。</p><code>{String(item.arguments.command||JSON.stringify(item.arguments))}</code><small>{chosenSpace?.path}<br/>批准仅适用于这一次操作 · {new Date(item.expires_at*1000).toLocaleTimeString()} 前有效</small><div>{item.expires_at*1000<=Date.now()?<button disabled={busy} onClick={()=>renew(item)}>审批已过期 · 续期后重新审阅</button>:<><button disabled={busy} onClick={()=>decide(item,false)}>拒绝</button><button className="primary" disabled={busy} onClick={()=>decide(item,true)}>批准执行 <Check size={14}/></button></>}</div></div>)}
      {children.length>0&&<div className="reply-box"><h3>子任务</h3>{children.map(child=><button className="space-item" key={child.id} onClick={()=>{setWorkspace(child.workspace_id);setSelected(child.id);}}><Layers3 size={18}/><span>{child.prompt.slice(0,80)}<small>{statusNames[child.status]} · {workspaces.find(space=>space.id===child.workspace_id)?.name||'独立工作区'}</small></span><ChevronRight size={16}/></button>)}</div>}
      {fileHistory.length>0&&<div className="reply-box"><label>文件变更记录 · 仅回退专用文件工具的修改</label>{fileHistory.map(file=><div className="file-change" key={file.call_id}><code>{file.path}</code><small>{file.restored?'已回退':`${file.before_hash?.slice(0,8)||'新文件'} → ${file.after_hash.slice(0,8)}`}</small>{!file.restored&&(allDone||task.status==='INTERRUPTED')&&<button disabled={busy} onClick={()=>act(async()=>{await api(`/file-actions/${task.id}/${allDone?'rewind':'reconcile'}`,{method:'POST',body:JSON.stringify({call_id:file.call_id,expected_revision:task.revision})});await refreshTask(task.id);})}>{allDone?'回退该文件':'核对写入结果'}</button>}</div>)}</div>}
      {task.status==='WAITING_INPUT'&&<div className="reply-box"><label htmlFor="reply">补充信息后继续</label><textarea id="reply" value={reply} onChange={e=>setReply(e.target.value)}/><button className="primary" disabled={busy||!reply.trim()} onClick={()=>control('input',reply)}>发送补充信息</button></div>}
      {allDone&&<div className="reply-box"><label htmlFor="followup">在此基础上继续</label><textarea id="followup" placeholder="补充一个新目标，将创建关联任务…" value={prompt} onChange={e=>setPrompt(e.target.value)}/><button className="primary" disabled={busy||!prompt.trim()} onClick={()=>createTask(task)}>创建跟进任务 <ArrowUpRight size={15}/></button></div>}</>:<div className="waiting">正在读取任务…</div>}</section>
      <aside className="evidence"><div className="evidence-tabs">{['成果','过程','来源'].map(name=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}>{name}{name==='成果'&&artifacts.length>0&&<small>{artifacts.length}</small>}</button>)}</div>{tab==='成果'?<div>{artifacts.length?artifacts.map(file=><button className="artifact" key={file.id} onClick={()=>download(file)}><FileText size={24}/><span>{file.name}<small>版本 {file.version} · SHA256 {file.sha256.slice(0,8)}</small></span><Download size={15}/></button>):<div className="empty-panel"><FileText size={31} strokeWidth={1}/><h3>成果会出现在这里</h3><p>报告和资料输出将保留版本，<br/>完成后可随时下载。</p></div>}</div>:tab==='来源'?<div>{sources.map(source=><a className="source" href={source.url} target="_blank" rel="noopener noreferrer" key={source.id}><Globe2 size={16}/><span>{source.title||source.url}<small>{source.url}</small></span><ArrowUpRight size={14}/></a>)}{!sources.length&&<p className="empty-small">还没有已读取的网页来源。</p>}</div>:<ol className="timeline">{events.filter(e=>!['text_delta','assistant_message'].includes(e.type)).map(event=><li key={event.sequence}><span className="timeline-point"/><small>#{event.sequence} · {new Date(event.created_at*1000).toLocaleTimeString()}</small><b>{event.type==='status'?statusNames[String(event.payload.status)]:event.type==='tool_started'?'执行工具':event.type==='tool_result'?'工具结果':event.type==='tool_prepared'?'准备工具':event.type==='approval_required'?'等待批准':event.type==='input_required'?'等待补充':event.type}</b><details><summary>{String(event.payload.name||event.payload.status||'查看详情')}</summary><pre>{JSON.stringify(event.payload,null,2)}</pre></details></li>)}</ol>}{task&&<div className="metrics"><div><span>模型请求</span><b>{task.metrics.model_requests}</b></div><div><span>工具调用</span><b>{task.metrics.tool_calls}</b></div><div><span>活动时间</span><b>{task.metrics.active_seconds.toFixed(1)} s</b></div><div><span>输入 / 输出 Token</span><b>{task.metrics.usage?(task.metrics.usage.complete?'':'部分统计：')+`${task.metrics.usage.input_tokens} / ${task.metrics.usage.output_tokens}`:'未提供'}</b></div></div>}</aside></div>}
      <footer>MUSE <span>·</span> 让想法成为成果</footer></main>
    {modal&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label={modal==='memory'?'记忆管理':'工作区管理'}><div className="modal-heading"><h2>{modal==='memory'?'记忆管理':'工作区管理'}</h2><button className="icon-button" aria-label="关闭弹窗" onClick={()=>setModal(null)}><X size={19}/></button></div>{modal==='memory'?<><p className="muted">你决定 MUSE 记住什么。删除后，新请求不再使用该记忆。</p><div className="memory-list">{memories.map(item=><article key={item.id}><div><b>{item.title}</b><small>{item.scope==='user'?'用户级':workspaces.find(w=>w.id===item.workspace_id)?.name||'项目级'}</small><p>{item.content}</p></div><button onClick={()=>{setMemoryId(item.id);setMemoryTitle(item.title);setMemoryContent(item.content);setMemoryScope(item.scope);if(item.workspace_id)setWorkspace(item.workspace_id);}}>编辑</button><button className="icon-button" aria-label={'删除记忆 '+item.title} onClick={()=>act(async()=>{await api('/memories/'+item.id,{method:'DELETE'});setMemories(await api('/memories'));})}><Trash2 size={16}/></button></article>)}</div><label>记忆标题<input value={memoryTitle} onChange={e=>setMemoryTitle(e.target.value)}/></label><label>记忆内容<textarea value={memoryContent} onChange={e=>setMemoryContent(e.target.value)}/></label><label>作用范围<select value={memoryScope} onChange={e=>setMemoryScope(e.target.value)}><option value="project">当前工作区</option><option value="user">所有工作区</option></select></label><button className="primary" disabled={busy||!memoryTitle.trim()||!memoryContent.trim()} onClick={saveMemory}>保存记忆</button></>:<><p className="muted">指定已有的本地文件夹，授权 MUSE 在其中完成任务。</p>{workspaces.map(space=><button key={space.id} className="space-item" onClick={()=>{setWorkspace(space.id);setModal(null);}}><FolderOpen size={18}/><span>{space.name}<small>{space.path}</small></span>{workspace===space.id&&<Check size={17}/>}</button>)}<label>工作区名称<input value={workspaceName} onChange={e=>setWorkspaceName(e.target.value)}/></label><label>文件夹绝对路径<input placeholder="C:\Projects\my-project" value={workspacePath} onChange={e=>setWorkspacePath(e.target.value)}/></label><button className="primary" disabled={busy||!workspacePath.trim()} onClick={()=>act(async()=>{const space=await api<Workspace>('/workspaces',{method:'POST',body:JSON.stringify({path:workspacePath,name:workspaceName||'工作区'})});setWorkspace(space.id);setWorkspaceName('');setWorkspacePath('');await refresh();setModal(null);})}>添加工作区</button></>}{error&&<p className="error" role="alert">{error}</p>}</section></div>}
  </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
